language: java

dist: trusty

jdk: 
- openjdk8

addons:
chrome: stable

services:
- xvfb

before_install:
- sudo apt-get install libgconf-2-4
- sudo apt-get update
- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update 
- sudo apt-get install google-chrome-stable
- sudo apt-get install libsqlite3-dev chromium-driver
#- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
- wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/chromedriver
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
- wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/chromedriver
- sudo chmod +x /usr/local/share/chromedriver
#- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- "export DISPLAY=:99.0"
- sleep 3 #give xvfb time to start
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
- mvn -Dtest=TestMernCrud test
